---
sudo: required
before_install:
  - wget -qO - https://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb http://packages.elasticsearch.org/logstash/2.3/debian stable main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update && sudo apt-get install logstash
script: |
  sudo /opt/logstash/bin/logstash-plugin install logstash-input-http_poller
  sudo /opt/logstash/bin/logstash-plugin install logstash-filter-prune
  sudo /opt/logstash/bin/logstash-plugin install logstash-output-riemann
  /opt/logstash/bin/logstash --configtest -f logstash/
